canonical/mysql-k8s-operator

- src/charm.py
Now we have a simple readinessProbe (#4 ) and livenessProbe (#5 )
> FIX #4 and #5

- metadata.yaml
- requirements.txt
- src/charm.py
> WIP: Add a method to check if mysql is up and running

- config.yaml
- src/charm.py
> FIX #25 - admin user for InnoDB Cluster 

- CONTRIBUTING.md
- INTEGRATING.md
- README.md
- Add INTEGRATING.md
- Add new sections to README.md
- Add new sections to CONTRIBUTING.md
> Improving documentations

- tests/integration/high_availability/test_self_healing.py
We have not yet implemented the test for a graceful restart of the primary unit.
Implement the test
Implement test for graceful restart of the primary unit
> Implement test for graceful restart of the primary unit

- docs/documentation_landing.md
- docs/tutorial.md
K8s copy of VM Tutorial https://github.com/canonical/mysql-operator/pull/98
> Add initial tutorial and Discourse landing pages

- src/relations/mysql_provider.py
- tests/unit/test_database.py
Just adding the database field in the provider side. This is to follow the interface signature change https://github.com/canonical/charm-relation-interfaces/pull/43
> [MISC] Add database field in the provider-side databag

- src/relations/mysql_provider.py
relation data could be incompletely set in case of k8s error (deferred event).
Move all setup of relation data to hook's end.
> Set relation data atomically at hooks end

- src/prometheus_alert_rules/metrics_alert_rules.yaml
no rules generates extra noise in logs
add basic rule
> Basic prometheus alert rule

- lib/charms/mysql/v0/mysql.py
- src/charm.py
- src/mysql_k8s_helpers.py
- tests/unit/test_charm.py
- tests/unit/test_mysql_k8s_helpers.py
> DPE-1231 create cluster set

- lib/charms/mysql/v0/mysql.py
- tests/integration/high_availability/test_self_healing.py
Same as [vm pr#242](https://github.com/canonical/mysql-operator/pull/242)
> Refactor get_member_state

- metadata.yaml
Switch maintainers to the DPE mailing list
> [MISC] Switch maintainers to the DPE mailing list

- lib/charms/mysql/v0/mysql.py
- src/charm.py
- src/mysql_k8s_helpers.py
- tests/unit/test_charm.py
Port of [vm's pr 296](https://github.com/canonical/mysql-operator/pull/296)
> dpe-2124 in lib config file render

- .github/workflows/ci.yaml
- lib/charms/data_platform_libs/v0/data_interfaces.py
- src/relations/mysql_provider.py
- tests/integration/relations/test_database.py
MySQL K8s wasn't using Relational Secrets that were made available in `data_platform_libs/data_interfaces.py` v18
Updateing the libraries, fixing small related issue in the code/tests
> [DPE-2205] data-platform-libs v19 external secrets

- src/upgrade.py
- tests/unit/test_upgrade.py
> DPE-2774 ensure cluster metadata node addresses consistency

- .github/workflows/sync_docs.yaml
https://github.com/canonical/mysql-k8s-operator/pull/306
> DPE-2981  discourse gatekeeper

- lib/charms/mysql/v0/tls.py
https://warthogs.atlassian.net/browse/DPE-3156
Ported from https://github.com/canonical/mysql-operator/pull/360
> Avoid setting secret upon tls relation broken if using juju secrets

- .github/workflows/ci.yaml
- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/data_platform_libs/v0/s3.py
- lib/charms/data_platform_libs/v0/upgrade.py
- lib/charms/mysql/v0/mysql.py
- lib/charms/mysql/v0/tls.py
- src/constants.py
- src/k8s_helpers.py
- src/relations/mysql.py
- src/relations/mysql_provider.py
- src/relations/mysql_root.py
- tests/unit/test_charm.py
Port of https://github.com/canonical/mysql-operator/pull/385
* Test code removed to avoid duplication. Source and tests are in VM charm (lib owner).
> DPE-3265 refactor for in lib secrets

- src/k8s_helpers.py
- src/mysql_k8s_helpers.py
- src/relations/mysql_provider.py
- tests/unit/test_database.py
- tests/unit/test_mysql_k8s_helpers.py
* current preemptive switchover does not update pod labels (for service selection)
* update pod labels on successful switchover
Closes #335
> DPE-2919 update pod labels on preemptive switchover

- .gitignore
- lib/charms/mysql/v0/mysql.py
[spec DA-050](https://docs.google.com/document/d/1wgetvkj4M_i03ZP-zGTcZh7-NhZWgqIgaiE9jGcwwJ0/edit)
Implement the disable operation
> DPE-2184 operator disable

- README.md
- docs/explanation/e-architecture.md
- docs/how-to/h-develop/h-develop-migratedataby/h-develop-backuprestore.md
- docs/reference/r-releases-group/r-releases-rev113.md
- docs/reference/r-releases-group/r-releases-rev75.md
- docs/reference/r-releases-group/r-releases-rev99.md
- docs/reference/r-requirements.md
"ROCK" should be "rock"
Just replaced all occurrences.
Also edited https://discourse.charmhub.io/t/charmed-postgresql-k8s-explanations-architecture/11856?_gl=1*194f4in*_gcl_au*MTc4NTc3NzUwMy4xNzE2MzkzMDQx*_ga*OTc0NDczODk5LjE2ODg1NDc0Njc.*_ga_5LTL1CNEJM*MTcxNjM5MzA0MC4xLjAuMTcxNjM5MzMyNC42MC4wLjA.&_ga=2.109885315.789167149.1716393041-20321142.1716393041
> chore: fix rocks terminology

- lib/charms/data_platform_libs/v0/upgrade.py
- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- poetry.lock
- pyproject.toml
- tests/integration/relations/test_mysql_root.py
**Chore**
* updated osm-bundle due issue with old bundle and newer juju
* bump libs
> pin pytest-asyncio

- src/charm.py
- src/config.py
See issue #400
- report_host is static configuration
- refactor flow to avoid event deferral
Fixes #400
> DPE-3896 report_host as static config

- src/charm.py
See issue #416
Skip defer for single unit, as done for VM charm already
Fixes #416
> DPE-4411 Fix restart for single-unit

- lib/charms/mysql/v0/async_replication.py
- lib/charms/mysql/v0/mysql.py
Port of [mysql-vm#467](https://github.com/canonical/mysql-operator/pull/467)
> DPE-4658 global-primary on endpoint

- lib/charms/mysql/v0/async_replication.py
- lib/charms/mysql/v0/mysql.py
- lib/charms/mysql/v0/tls.py
- src/charm.py
- src/log_rotate_manager.py
- src/relations/mysql.py
- src/relations/mysql_provider.py
- src/relations/mysql_root.py
- src/rotate_mysql_logs.py
- tests/unit/test_charm.py
- tests/unit/test_database.py
- tests/unit/test_upgrade.py
See issue #457
* avoid using juju for cluster initialization state
* allow catch all on non-critical/retried handler
Fixes #457
> DPE-4850 Fix intermitent issue on aks deployments

- lib/charms/mysql/v0/s3_helpers.py
This PR ports PostgreSQL operator `_construct_endpoint` helper function ([see code](https://github.com/canonical/postgresql-operator/blob/c5c916d41d00849da5ae657cba4c97c46cb3caad/src/backups.py#L229-L249)) , in order to support the specification of the old S3 endpoints format (i.e. `https://s3.amazonaws.com`), stated in the [charm docs](https://charmhub.io/mysql-k8s/docs/h-configure-s3-aws).
I decided to port the helper, instead of updating the docs, in order to make MySQL operator support as similar to PostgreSQL operator as possible. If we eventually decide to stop supporting the old S3 endpoints format, we will do so across our repositories, and not across a sub-set of them.
> [DPE-5908] Support old bucket endpoints format

- config.yaml
- lib/charms/mysql/v0/mysql.py
- src/charm.py
- src/config.py
- src/constants.py
- src/log_rotation_setup.py
- src/mysql_k8s_helpers.py
- src/upgrade.py
- templates/logrotate.j2
- tests/integration/helpers.py
- tests/integration/high_availability/test_log_rotation.py
- tests/integration/high_availability/test_self_healing.py
- tests/unit/test_mysql_k8s_helpers.py
Port of vm [PR#597](https://github.com/canonical/mysql-operator/pull/597) - Implementation of DA124
> feat: DPE-5656 log rotation new options

- metadata.yaml
- src/dependency.json
There is a new ROCK with an update of MySQL to v8.0.41
Update the ROCK tag and also update MySQL to v8.0.41
> Update MySQL version to 8.0.41

- metadata.yaml
We have new rock builds that include new versions of percona packages
Update rock image
> [DPE-6651] Update rock tag for new builds with updated percona packages

- tox.ini
> Create coverage report for tiobe

- lib/charms/mysql/v0/async_replication.py
- lib/charms/mysql/v0/backups.py
- lib/charms/mysql/v0/mysql.py
- src/charm.py
- src/k8s_helpers.py
- src/mysql_k8s_helpers.py
- src/relations/mysql_provider.py
- src/upgrade.py
- tests/unit/test_k8s_helpers.py
- tests/unit/test_mysql_k8s_helpers.py
This PR updates the MySQL charm libs after merging the Juju Spaces support [PR](https://github.com/canonical/mysql-operator/pull/643) in its VM counterpart.
To see adaptations to the codebase:
- https://github.com/canonical/mysql-k8s-operator/pull/621/commits/1e1e50c81d6668587f1a79cdbe2c60524b051da3
- https://github.com/canonical/mysql-k8s-operator/pull/621/commits/b306c37bf7aacd8793e290f4a802dcb36596be1c
- https://github.com/canonical/mysql-k8s-operator/pull/621/commits/f5efdedf22eb6ab7d3c7f74a4ea07308f2a6e9c1
> [MISC] Update MySQL charm libs

- docs/explanation/roles.md
- lib/charms/mysql/v0/mysql.py
- tests/integration/roles/test_database_dba_role.py
This PR is a counterpart of this [VM](https://github.com/canonical/mysql-operator/pull/684) one.
> [DPE-7322] Tweak database DBA role naming
