canonical/mysql-k8s-operator

- config.yaml
> FIX #20 - Empty password string causes error while deploying

- src/charm.py
- src/mysqlsh_helpers.py
1. We modify `group_replication_ip_allowlist` on the juju leader unit when adding instances to the cluster. We maintain all instances' hosts in the peer relation databag. However, we should not be modifying this value.
2. When we call `_run_mysqlsh_script` or `_run_mysqlcli_script` (to execute either a mysqlsh script or mysql script), we log any errors. However, we also follow a pattern where the calling method logs its own errors/exceptions. Therefore, the error logs in `_run_mysqlsh_script` or `_run_mysqlcli_script` is extraneous.
1. Do not modify the `group_replication_ip_allowlist`
2. Remove the extraneous logs
Do not modify group replication ip allowlists
> Do not modify allowlists and remove extraneous logger statements

- src/mysqlsh_helpers.py
We are running into this [issue/error trace](https://github.com/canonical/mysql-k8s-operator/runs/7434800404?check_suite_focus=true#step:4:6640) when running integration tests on github actions.
[Further research](https://dev.mysql.com/doc/refman/8.0/en/group-replication-options.html#sysvar_group_replication_ip_allowlist) shows that connections in the group may be refused if the protocol is different that the one in the `group_replication_ip_allowlist`. Since we are setting an ipv4 cidr (`0.0.0.0/0`), connections from ipv6 addresses are being refused.
Set the `group_replication_ip_allowlist` as `0.0.0.0/0,::/0` to allow any ipv4 or ipv6 address.
Enable nodes with IPV6 addresses in the group replication
> Enable nodes with IPV6 addresses in the group replication 

- .github/workflows/release.yaml
Integration tests in release to charmhub CI are [failing](https://github.com/canonical/mysql-k8s-operator/runs/7454554979?check_suite_focus=true). The same integration tests are passing in the normal CI job. The only difference I can find is the microk8s and juju versions.
Pin the microk8s version to 1.23 and juju version to 2.9.29 (the same as the other CI job)
Pin integration test microk8s environment
> Pin integration test microk8s environment

- tox.ini
There is a known [issue](https://github.com/PyCQA/flake8/issues/1635) where pflake8 monkey patches flake8 which is now allowed. Due to this, linting check error out.
Pin flake8 to version `4.0.1` until the [following PR](https://github.com/csachs/pyproject-flake8/pull/14) resolving the issue is merged.
> Pin flake8 version for linting to temporarily resolve lint errors

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
Auto publishing is failing due GHA(GitHub Action) issue.
Bump charmhub upload GHA version.
Remove reduntant test execution when merge to main.
> Fix auto publish

- lib/charms/mysql/v0/mysql.py
- src/relations/database.py
- tests/integration/test_database.py
We have not yet ported over the `mysqlrouter` extra user roles in the database relation interface. This role is used to create a user used by mysqlrouter to bootstrap and additionally needs to be granted `CREATE USER` privileges.
Port over the `mysqlrouter` extra user roles. Use `mysqlsh.cluster.setup_router_account({update: 1})` to set up the bootstrap user. Create helper method to grant `CREATE USER` privileges to this user.
Add mysqlrouter extra user roles for the database relation interface
> Add mysqlrouter extra user roles for the database relation interface

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- tests/integration/helpers.py
- tests/integration/test_charm.py
1. Alex introduced a dependency for tests (to save time and cycles running heavy integration tests if unit tests or lints fail). We do not yet have this in this repository
2. We are not raising on blocked in the `scale_application` helper function
3. Somehow, scaling the database more than one unit at a time is causing the following error trace (https://github.com/canonical/mysql-k8s-operator/actions/runs/3204633434/jobs/5236555089#step:4:541). Not suggesting that this is the root cause
1. Replicate the dependencies for tests to this repo
2. Raise on blocked
3. Scale up one application at a time to see if that reduces the frequency of the error
Replicate CI job dependency + try to address flakiness of tests
> Replicate CI job dependency + try to address flakiness of tests

- lib/charms/mysql/v0/mysql.py
- tests/integration/relations/application-charm/src/charm.py
- We introduced a [fix](https://github.com/canonical/mysql-operator/pull/50) for not properly escaping `database-name`, `username` and `hostname` while forming application relation. However, we have not yet imported this fix into this repository.
Import the fix by fetching the latest version of the `mysql` library. Update the `relations` application-charm to use `-`s in database name when trying to form a relation with the database.
Fetch updated mysql lib to resolve unescaped database identifiers
> Fetch updated mysql lib to resolve unescaped database identifiers

- .github/workflows/ci.yaml
- actions.yaml
- charmcraft.yaml
- lib/charms/mysql/v0/mysql.py
- lib/charms/rolling_ops/v0/rollingops.py
- lib/charms/tls_certificates_interface/v1/tls_certificates.py
- metadata.yaml
- pyproject.toml
- requirements.txt
- src/charm.py
- src/constants.py
- src/mysqlsh_helpers.py
- src/relations/mysql.py
- src/relations/mysql_tls.py
- src/relations/osm_mysql.py
- templates/tls.cnf
- tests/integration/connector.py
- tests/integration/helpers.py
- tests/integration/relations/application-charm/src/charm.py
- tests/integration/relations/application-charm/src/connector.py
- tests/integration/test_tls.py
- tests/unit/test_charm.py
- tox.ini
TLS support for MySQL k8s charm.
Ref. tasks:
[DPE-641](https://warthogs.atlassian.net/browse/DPE-641), [DPE-643](https://warthogs.atlassian.net/browse/DPE-643), [DPE-644](https://warthogs.atlassian.net/browse/DPE-644) and [DPE-645](https://warthogs.atlassian.net/browse/DPE-645)
This is the port of pretty much the same codebase from MySQL VM [PR48](https://github.com/canonical/mysql-operator/pull/48) that's already approved. The main differences are:
* included integration tests
* modifications to work under k8s
Tests implemented as integration test at `tests/integration/test_tls.py`
*quick math: it looks big to the incautious eyes at +2382-39 lines, but ignoring new libs being added/updated it's only +770 lines, so fear not*
**Important changes**:
* `actions.yaml` - TLS action
* …
> Feature TLS support

- .github/workflows/release.yaml
There's an issue on publishing k8s charm when downloading OCI
Bumping to the latest version should fix
> Bump action to fix charm release

- src/charm.py
- src/mysql_k8s_helpers.py
- tests/integration/high_availability/test_replication.py
- tests/integration/high_availability/test_self_healing.py
- tests/unit/test_mysql_k8s_helpers.py
- tests/unit/test_mysqlsh_helpers.py
Since there is an issue with juju in k8s (where teardown event dont fire), we use `force remove instance` from the cluster to remove scaled down units. However, we are currently (on leader-elected and peer-relation-departed) removing all unreachable instances from the cluster. This is problematic as an instance could be unreachable due to a network partition, but should be able to rejoin the cluster once the partition has been resolved.
Only `force remove instance`s that are scaled down. For this, we rely on `planned units` (which returns the number of planned units for an application) and the fact that juju with k8s provisions units in sequence 0, 1, 2,... Thus we will only remove any instance from the cluster whose index is >= planned units.
Refactor scale down logic to not blindly …
> Refactor scale down logic to not blindly remove all unreachable instances from the cluster

- src/charm.py
- tests/integration/helpers.py
`get_cluster_status()` returns None on failure,
so that must be accounted for when setting the get-cluster-status
action results dictionary.
Also ensure that this `None` return value is documented
and accounted for elsewhere in the code where it wasn't previously.
> Tidy get-cluster-status action output on failure

- .github/workflows/ci.yaml
- .github/workflows/promote.yaml
- .github/workflows/release.yaml
- tests/integration/high_availability/scripts/deploy_chaos_mesh.sh
- tests/integration/high_availability/scripts/destroy_chaos_mesh.sh
- tox.ini
We are using more and more shell (bash) scripts but have no static code analyses for them.
Use `shellcheck` to make sure our shell scripts are OK.
GH Action for now and tox.ini to test locally.
Test all shell scripts using `shellcheck`.
> DPE-1116 Add shellcheck GH Action

- lib/charms/mysql/v0/mysql.py
- src/charm.py
- src/mysql_k8s_helpers.py
- src/relations/mysql.py
- tests/integration/relations/test_database.py
- tests/integration/test_tls.py
- tests/unit/test_charm.py
[DPE-1223](https://warthogs.atlassian.net/browse/DPE-1223)
1. we are not checking if the member relating with the `mysql` interface is online when forming the relation
2. we are using the `root` mysql user to query users to delete (in `delete_users_for_unit`). the root user is unable to connect with the `mysql` client (using a unix socket)
1. if a relation is formed before the leader instance goes into `online` state, defer the formation of the relation until it is `online`
2. use the `serverconfig` user to query users to delete
```
juju deploy --channel=latest/edge --trust --resource keystone-image=opensourcemano/keystone:testing-daily osm-keystone keystone
juju deploy -n 1 ./mysql-k8s_ubuntu-22.04-amd64.charm --resource mysql-image=dataplatformoci/mysql-and-shell:latest --config …
```
> Attempt to fix errors while relating/unrelating kubeflow using mysql interface

- src/relations/mysql.py
We are spitting out a lot of info statements when deferring events
See [the following pastebin](https://pastebin.canonical.com/p/P5VVP8Q4DZ/) for such logs
Noop and return from the peer relation changed event handler if `mysql` relation does not exist. 
Noop peer relation changed event handler for mysql relation if relation does not exist
> Noop peer relation changed event handler for mysql relation if relation does not exist

- lib/charms/mysql/v0/mysql.py
- src/k8s_helpers.py
- src/relations/mysql_provider.py
- tests/integration/high_availability/application_charm/src/connector.py
- tests/integration/high_availability/application_charm/src/continuous_writes.py
- tests/unit/test_database.py
- tox.ini
Offline pods are now being set as offline and being used selected by the kubernetes service.
Related to [DPE-1225](https://warthogs.atlassian.net/browse/DPE-1225)
Fix endpoint setting by parsing offline nodes and setting pod label accordingly.
+Lib bump.
[DPE-1225]: https://warthogs.atlassian.net/browse/DPE-1225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix update pod labels

- tests/integration/relations/test_osm_mysql.py
The osm-zookeeper unit is constantly switching his status between `active` and `maintenance` (in integration tests):
> juju show-status-log osm-zookeeper/0
> Time                        Type       Status       Message
> ...
> 16 Feb 2023 11:30:18+01:00  workload   active       ready
> 16 Feb 2023 11:30:22+01:00  workload   maintenance  Sending Zookeeper configuration
> 16 Feb 2023 11:30:22+01:00  workload   active       ready
> 16 Feb 2023 11:30:30+01:00  workload   maintenance  Sending Zookeeper configuration
> 16 Feb 2023 11:30:31+01:00  workload   active       ready
> 16 Feb 2023 11:30:39+01:00  workload   maintenance  Sending Zookeeper configuration
> 16 Feb 2023 11:30:39+01:00  workload   active       ready
> 16 Feb 2023 11:30:49+01:00  workload   maintenance  Sending Zookeeper …
> Check osm-zookeeper status in a special way

- tests/integration/relations/test_osm_mysql.py
Otherwise the test produces warning:
> =============================== warnings summary ===============================
> tests/integration/relations/test_osm_mysql.py::test_deploy_and_relate_osm_bundle
>   /home/runner/work/mysql-k8s-operator/mysql-k8s-operator/tests/integration/relations/test_osm_mysql.py:112: RuntimeWarning: coroutine 'Model.block_until' was never awaited
>     ops_test.model.block_until(ops_test.model.applications["osm-zookeeper"].status == "active")
>   Enable tracemalloc to get traceback where the object was allocated.
>  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
await for model.block_until(ops_test.model.applications["osm-zookeeper"]...f
> Fix 618fe32d: wait for coroutine 'Model.block_until'

- metadata.yaml
The interface name is using `-`, but naming convention says `_`.
https://juju.is/docs/sdk/styleguide
The endpoint name should use `-`, but interface name `_`.
> Update peer interface name to follow naming conventions

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/high_availability/application_charm/lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/relations/application-charm/lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/test_backups.py
- We have updated the credentials for AWS to use the shared team account bucket (`data-charms-testing`). However, we have not yet updated our tests to use this bucket.
- The data_interface charm library is out of date
- Update backups integration tests to use `data-charms-testing` bucket and `mysql-k8s` as the path to store the backups
- Update the data_interface charm library in the mysql-k8s charm and the test application charms as well
> Update AWS bucket for backups integration tests

- src/charm.py
mysql-router can't connect to mysql cluster nodes on CMR, due nodes reporting self address without full domain, e.g. missing the `<model-name>.svc.cluster.local` and it silently fails to provide the read-only and read-write endpoints.
[DPE-1329](https://warthogs.atlassian.net/browse/DPE-1329)
Make each cluster node report it's address with the fully qualified domain name.
[DPE-1329]: https://warthogs.atlassian.net/browse/DPE-1329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> report host with fully qualified domain name

- src/charm.py
Transient issue where adding new units to a cluster with a to-be recovered primary has not yet recovered.
As described [DPE-1224](https://warthogs.atlassian.net/browse/DPE-1224).
Sets maintenance status for all cases (unit configured or not), which will defer new units joining the cluster until `Active Status` is reached.
Speed up recovery when restarting from a pre-configured attached storage.
During testing, sometimes the databag went missing and I could see [this bug in action](https://bugs.launchpad.net/juju/+bug/2011277)
[DPE-1224]: https://warthogs.atlassian.net/browse/DPE-1224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix new units addition after failure.

- src/mysql_k8s_helpers.py
- tests/integration/helpers.py
- tests/integration/high_availability/high_availability_helpers.py
The test is getting wrong pid due to wide match:
```
> ubuntu@juju-82de18-16:~$ pgrep -a mysqld
> 3774 /snap/charmed-mysql/24/bin/mysqld_exporter ...
> 3996 /bin/sh /snap/charmed-mysql/24/usr/bin/mysqld_safe ...
> 4866 /snap/charmed-mysql/24/usr/sbin/mysqld ...
> ubuntu@juju-82de18-16:~$
> ubuntu@juju-82de18-16:~$ pgrep -a -x mysqld
> 4866 /snap/charmed-mysql/24/usr/sbin/mysqld ...
> ubuntu@juju-82de18-16:~$
```
Use "pgrep -x" for exact match.
> Use exactly match on 'pgrep mysqld' due to mysqld_exporter availability

- docs/tutorial.md
We documented VM approach to scale K8s application.
Switch from `add/remove-unit` to `scale-application` (see details [here](https://github.com/canonical/postgresql-k8s-operator/pull/115#discussion_r1142749734)).
Meanwhile, simplify TLS check and improve tutorial working noticed recently.
> Switch K8s tutorial from add/remove-unit to scale-application

- docs/how-to/h-configure-s3.md
- docs/how-to/h-create-and-list-backups.md
- docs/how-to/h-enable-encryption.md
- docs/how-to/h-manage-app.md
- docs/how-to/h-manage-units.md
- docs/how-to/h-migrate-cluster-via-restore.md
- docs/how-to/h-restore-backup.md
To close the sprint epic we need to provide How-to documentation section.
Prepare a common structure, the similar to MongoDB and PostgreSQL how-to.
> Add how-to documents (based on PostgreSQL how-to)

- src/charm.py
- src/k8s_helpers.py
- src/mysql_k8s_helpers.py
- src/relations/mysql_provider.py
- src/utils.py
- tests/integration/high_availability/high_availability_helpers.py
- tests/unit/test_k8s_helpers.py
- tests/unit/test_mysql_k8s_helpers.py
- tests/unit/test_utils.py
The charm does not respect resources limits.
**Extra context**: the method to calculate memory limits is very grabby and uses host system memory as base.
Further tuning may be necessary on k8s as the k8s cluster node workload tends to be more diverse, requiring a somewhat less grabby calculation.
Refactor method that retrieve total memory to check for resources limits.
Chore:
- moved KubernetesHelpers reference from relation provider to charm in order to refer the object broadly
- refactor/added unit tests
Refer to [DPE-1598](https://warthogs.atlassian.net/browse/DPE-1598)
Closes #192 
[DPE-1598]: https://warthogs.atlassian.net/browse/DPE-1598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add support for memory constrained deployment

- CONTRIBUTING.md
- README.md
The README file was way outdated and had no interfaces description, causing issues like https://github.com/canonical/mysql-k8s-operator/issues/198
Update README to match the one in mysql VM repo.
We should consider for the future:
* name endpoints and interfaces identically/similar
* sync amount of interfaces supported by VM and K8s
> Update README to be up-2-date and describe supported relations

- metadata.yaml
We are using a ROCK label `charmed-mysql:8.0.32-22.04_edge` in the charm. However, a breaking a change in a new version of the ROCK can result in a broken charm. Additionally, it is possible for 2 nodes in the same cluster to have different versions of the ROCK (if a new version of the ROCK is released before a new node is added to the cluster).
Pin the ROCK to a specific hash in the metadata file. We can add a renovate configuration to update this hash in a future PR (to automatically update and create a PR when there is a new version of the ROCK).
> Pin the charmed-mysql rock to a hash

- src/relations/mysql.py
Replicas fail trying to get cluster primary before being added to the cluster on update_status hook for legacy mysql.
[DPE-1227](https://warthogs.atlassian.net/browse/DPE-1227) 
Skip hook when not initialized.
[DPE-1227]: https://warthogs.atlassian.net/browse/DPE-1227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> skip update when unit not ready

- src/relations/mysql.py
- tests/integration/high_availability/high_availability_helpers.py
mysql legacy relation will only accept configuration before relation is established, i.e. stuck on blocked and have no action even after the relation configuration is set.
Add capability to configure relation after relation is established.
> Allow delayed config for mysql legacy

- src/charm.py
planned units is flaky
This is related to [DPE-915](https://warthogs.atlassian.net/browse/DPE-915), since enables correctly removal of departing unit.
Unit departed still refuses to go away in `terminated` state, but it's possible to scale up over the `terminated` unit(s).
using peer databag units mapping instead
[DPE-915]: https://warthogs.atlassian.net/browse/DPE-915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> avoid flaky planned units

- src/charm.py
- src/mysql_k8s_helpers.py
- tests/unit/test_charm.py
The charm `mysql-k8s` cannot be deployed to AWS EKS, GKE, Charmed Kubernetes with an error:
```
ERROR unit.katib-db/0.juju-log   mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (OS errno 13 - Permission denied)
```
Fixes https://github.com/canonical/mysql-k8s-operator/issues/237, https://github.com/canonical/mysql-k8s-operator/issues/239,  [DPE-1919](https://warthogs.atlassian.net/browse/DPE-1919), [DPE-2064](https://warthogs.atlassian.net/browse/DPE-2064), [DPE-2066](https://warthogs.atlassian.net/browse/DPE-2066).
Set the proper owner for the DB Data folder (to be accessible by database).
See more details in [DPE-1919](https://warthogs.atlassian.net/browse/DPE-1919?focusedCommentId=254368).
[DPE-1919]: https://warthogs.atlassian.net/browse/DPE-1919?atlOrigin=eyJpIjoiNWRkN …
> DPE-2064 fix datadir permissions via chmod

- charmcraft.yaml
- src/charm.py
- src/mysql_k8s_helpers.py
- tests/integration/test_charm.py
- tests/unit/test_charm.py
Failing to reuse previously storage on the charm.
If data directory is populated with mysql typical data, the charm tries to use start mysqld and rejoin the unit to the cluster.
_Note 1: The `unit-configured` unit peer key, that indicate if a unit was already configured, was replaced with a method to check the mysql data directory directly._ 
_Note 2: case there's a `clusteradmin` password rotation before the scale up, joining the unit will fail, since the passwords will be out of sync. There's a backlog task (dpe-2186) to track this scenario._
> DPE-915 fix storage re-use bug

- actions.yaml
- src/charm.py
We are raising an exception when an invalid username is passed to the get-password or set-password action.
Use event.fail to return a more meaningful message (instead of raising an exception).
> Fail action to set or get incorrect user password

- src/charm.py
- src/mysql_k8s_helpers.py
- tests/integration/helpers.py
- tests/integration/test_charm.py
- tests/unit/test_charm.py
Ported from vm merged [PR#223](https://github.com/canonical/mysql-operator/pull/223)
> DPE-2069 max_connections auto tune

- tox.ini
- We are unable to run tests due to https://github.com/juju/python-libjuju/issues/914
Pin macaroonbakery to 1.3.1
Update pin of juju to 2.9.43.0
> Update juju pin to 2.9.43.0 and pin macaroonbakery to 1.3.1 in tox

- .github/workflows/sync_discourse.yaml
In the PR #251 , a change was erronously merged that created a tag not in the main branch and also provided incorrect settings for the run
The `true` flag needs to be kept with quote as per the comment [here](https://github.com/canonical/mysql-k8s-operator/pull/251#discussion_r1260904709)
> [MISC] Revert change on Discourse Sync action

- requirements.txt
- src/charm.py
- src/mysql_k8s_helpers.py
- tests/unit/test_charm.py
- tests/unit/test_mysql_k8s_helpers.py
Workaround for pebble fixed 5s delay `SIGKILL` after `SIGTERM`
**BLOCKED BY**: ~ops [PR#975](https://github.com/canonical/operator/pull/975)~ next ops release (2.5.0 maybe?)
Use kill-delay
> DPE-2068 use kill-delay

- lib/charms/mysql/v0/backups.py
- lib/charms/mysql/v0/mysql.py
- src/charm.py
- src/k8s_helpers.py
- src/mysql_k8s_helpers.py
- tests/integration/helpers.py
- tests/integration/high_availability/test_self_healing.py
- tests/integration/relations/test_mysql_root.py
- tests/integration/test_charm.py
- tests/unit/test_charm.py
Mysqld should not use node total memory for parameters auto tuning.
* Use k8s allocable memory as baseline for usable memory.
* consider `group_replication_message_cache_size` for calculating available pool size
* use smaller possible `group_replication_message_cache_size` when using `testing` profile
Extra: [The commit](https://github.com/canonical/mysql-k8s-operator/pull/256/commits/a1fb0332c24d9461f9ddead70e24bdb591b4ad30) address [DPE-2274](https://warthogs.atlassian.net/browse/DPE-2274) 
closes #254 
[DPE-2274]: https://warthogs.atlassian.net/browse/DPE-2274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DPE-2225 using allocable memory instead of `free`

- tests/integration/high_availability/conftest.py
- tests/integration/high_availability/high_availability_helpers.py
- tests/integration/high_availability/scripts/destroy_chaos_mesh.sh
Flakiness on the network partition test
* ensure chaos-mesh availability before test
* fixes destroy script
* function scoped
> Fixes for network partition test

- src/relations/mysql.py
- src/relations/mysql_root.py
We cannnot use `_` in secret keys (for password keys in legacy relations). Some applications already deployed will use `_` in peer relation secrets, but when secrets are rotated, they must be rotated with `-` in juju secrets rather than `_`
Use `fallback_key` with `_` (as done in mysql vm [PR 243](https://github.com/canonical/mysql-operator/pull/243/files#diff-a7f1a6521d2009b594920ca3bb3ecec524f52fced6c7670d281ed5b335a608f6R504-R524)), but first try to store/get secrets with `-`
> DPE-2408 Use fallback key for passwords in legacy relations

- src/charm.py
- tests/unit/test_charm.py
- tox.ini
On scale down of primary, MySQL will reelect the primary after some delay.
Minimize delay by preemptively setting primary to unit 0 (last one to be torn down) if primary is being removed.
> DPE-2217 premptively switchover

- lib/charms/mysql/v0/mysql.py
- src/mysql_k8s_helpers.py
We updated the `mysql` charm lib with some feature, one of which includes not configuring the `root@%` user. We have not yet imported this charm lib into this charm.
Import the most up to data version of the `mysql` charm lib
> DPE-2178 Update mysql charm lib to v0.44 - to stop configuring mysql user root@%

- metadata.yaml
- tests/integration/high_availability/test_upgrade.py
- tests/integration/test_tls.py
We built a new rock for 8.0.34, but this charm still uses the rock for 8.0.33
Update the rock
> DPE-2426 Update mysql image to 8.0.34 rock

- src/charm.py
COS relation creation/departure is reconciling the pebble layer, which will hinder the charm initialization in case it happens before other initial events (leader-election, pebble-ready).
This scenario will happens on relating with COS right from the deployment, e.g. in a bundle.
Defer handler to run after initialization.
> [bugfix] defer reconciling pebble layer for exporter

- src/dependency.json
Again, I merged in the changes to switch the ROCK to 8.0.34, but missed changes in upgrade dependencies
Update the upgrade dependencies
> DPE-2426 Update upgrade dependencies for mysqld and charm to account for 8.0.34

- .github/workflows/ci.yaml
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/integration/high_availability/scripts/deploy_chaos_mesh.sh
- tests/integration/high_availability/scripts/destroy_chaos_mesh.sh
- tests/integration/test_backups.py
- tests/unit/test_charm.py
- tox.ini
Current pipelines are only supporting Juju2
Extending pipelines with a matrix also executing Juju3.
Note that this triggers usage of Juju Secrtets (internal so far), which requires changes on tests
> [DPE-2684] Juju3 pipelines

- charmcraft.yaml
- lib/charms/mysql/v0/mysql.py
- metadata.yaml
- poetry.lock
- pyproject.toml
- scripts/log_rotate_dispatcher.py
- src/charm.py
- src/constants.py
- src/log_rotate_manager.py
- src/mysql_k8s_helpers.py
- src/rotate_mysql_logs.py
- templates/logrotate.j2
- templates/logrotate.yaml.j2
- tests/integration/helpers.py
- tests/integration/high_availability/high_availability_helpers.py
- tests/integration/high_availability/test_self_healing.py
- tests/integration/test_charm.py
- tests/unit/test_charm.py
- tox.ini
1. We currently do not have general or slowquery logs enabled (discussion pending whether slowquery logs should be enabled)
2. We would like to rotate the error, general and slowquery logs
1. Enable general and slowquery logs (may remove the enable-ment of slowquery logs pending discussion with mohamed)
2. Rotate the text logs. To do so, we copy the logrotate config upon instance configuration. Furthermore, we add to the charm container pebble layer a service that runs a script. This script tries its best to dispatch a custom event to rotate (by running logrotate with pebble exec) and flush logs at the top of every minute
> DPE-1797 Implement log rotation of error, general and slowquery logs

- .github/workflows/ci.yaml
- CONTRIBUTING.md
- poetry.lock
- pyproject.toml
- tox.ini
https://github.com/canonical/mysql-k8s-operator/pull/313 introduced a mandatory requirement on running unittests. 
Now we're pinning down Juju3 as default.
> [DPE-2737] Fix unittest tox defaults to run Juju3 tests by default

- lib/charms/mysql/v0/mysql.py
- src/charm.py
- src/log_rotate_manager.py
- src/rotate_mysql_logs.py
- tests/integration/high_availability/high_availability_helpers.py
When we scale up to more than one unit, it is possible that we start the log rotate dispatcher before the unit is fully initialized (and the logrotate config file is copied over the workload container).
```
unit-mysql-k8s-2: 18:00:00 ERROR unit.mysql-k8s/2.juju-log Failed to rotate mysql logs
Traceback (most recent call last):
File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 646, in _execute_commands
stdout, stderr = process.wait_output()
File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 1359, in wait_output
raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['logrotate', '-f', '/etc/logrotate.d/flush_mysql_logs'], stdout='', stderr='error: cannot stat …
```
> Prevent starting logrotate dispatcher or flush mysql logs until unit initialized

- lib/charms/mysql/v0/mysql.py
- src/charm.py
- src/upgrade.py
1. mysqlsh will fail on same version check
1. single unit won't reconnect to a cluster (as it is the cluster)
1. `reboot_from_complete_outage` will not recognize unit as part of the cluster in it's metadata due to the `report_host` not being equal to the unit's fqdn (`hostname.mysql-k8s-endpoints != hostname.mysql-k8s-endpoints.model.svc.cluster.local`)
1. modify mysqlsh version verification command to accommodate same versions correctly 
1. make usage of `reboot_from_complete_outage` for single unit deployment recovery
1. use fqdn for mysql's `report_host`
Merge after vm [PR#340](https://github.com/canonical/mysql-operator/pull/340)
Fixes #317
> DPE-2661 single unit upgrade fixes

- lib/charms/mysql/v0/s3_helpers.py
We were use `lstrip` in a helper that determined which backups are available in the `list-backups` action. What we actually wanted was `remove_prefix`
Fetch in a new version of the `s3_helpers` charm lib which has the above fix
> Fix bug that resulted in wrong output displayed from list-backups action

- lib/charms/data_platform_libs/v0/data_secrets.py
- lib/charms/mysql/v0/mysql.py
- poetry.lock
- pyproject.toml
- tests/unit/test_charm.py
> [DPE-2885] Secret labels

- templates/logrotate.j2
We are using `-%V_%H%M` as the dateformat for logrotate - this causes filename conflicts after a day of uptime due to file name conflicts.
Use `-%Y%m%d_%H:%M` as the dateformat (for consistency with pgbouncer)
`-%u` in the dateformat does not get correctly substituted as per the docs:
```
error: destination /var/log/mysql/archive_general/general.log-%u_1637 already exists, skipping rotation
root@mysql-k8s-0:/# ls -la /var/log/mysql/archive_error/
total 8
drwxrwx--- 2 mysql mysql 4096 Nov 30 16:37 .
drwxr-xr-x 1 mysql mysql 4096 Nov 30 16:37 ..
-rw-r----- 1 mysql mysql    0 Nov 30 16:36 error.log-%u_1637
```
> [DPE-3063] Change dateformat in logrotate config to avoid causing filename conflicts after 24hrs of uptime

- src/mysql_k8s_helpers.py
Charm deployment lands in an error state, mostly on GitHub Actions runners.
The error is caused by  `config-changed` hook failure when calling the `is_mysqld_running` method.
<details>
<summary>
Error snippet out of `kubectl logs mysql-k8s`
</summary>
```
unit-mysql-k8s-0: 16:48:16 ERROR unit.mysql-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/./src/charm.py", line 786, in <module>
main(MySQLOperatorCharm)
File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 436, in main
_emit_charm_event(charm, dispatcher.event_name)
File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
event_to_emit.emit(*args, **kwargs)
File …
```
> DPE-3027 Retry policy for is_mysqld_running 

- lib/charms/mysql/v0/mysql.py
- poetry.lock
- pyproject.toml
- src/charm.py
- src/k8s_helpers.py
- src/mysql_k8s_helpers.py
- src/rotate_mysql_logs.py
- tests/integration/test_charm.py
- tests/unit/test_charm.py
- tests/unit/test_k8s_helpers.py
- tests/unit/test_mysql_k8s_helpers.py
Workload containers get restarted due timeout on livenessProbe pebble endpoint.
Discussion at juju lp bug: https://bugs.launchpad.net/bugs/2052517
Here some mitigations and optimizations, not a final solution though.
* set floor for max_connections in 100
* function retries
* flush logs in single call
* + test coverage
> DPE-3547 mitigations for container restart

- lib/charms/mysql/v0/s3_helpers.py
Port of VM [PR#396](https://github.com/canonical/mysql-operator/pull/396)
Fixes #382
> DPE-3617 add ca chain support

- src/charm.py
- src/mysql_k8s_helpers.py
- src/relations/mysql_provider.py
- src/rotate_mysql_logs.py
- src/upgrade.py
- tests/integration/high_availability/high_availability_helpers.py
- tests/integration/high_availability/test_upgrade.py
- tests/integration/high_availability/test_upgrade_from_stable.py
- tests/integration/high_availability/test_upgrade_rollback_incompat.py
- tests/unit/test_charm.py
- tests/unit/test_upgrade.py
Upgrade rollback fails when new mysqld modify data_dir without backward compatibility.
Add treatment for the case that data_dir is modified, for multi-unit cluster (reset and clone)
> DPE-3389 support rollback incompat data dir 

- metadata.yaml
- src/dependency.json
We built a new ROCK for 8.0.36 that we are not using in the charm
Update ROCK image
> [DPE-3717] Update ROCK to 8.0.36

- config.yaml
- lib/charms/mysql/v0/mysql.py
- src/charm.py
- src/config.py
Port of [VM #429](https://github.com/canonical/mysql-operator/pull/429)
> DPE-3706 experimental max_connections

- metadata.yaml
juju [bug](https://bugs.launchpad.net/juju/+bug/2065284) affecting k8s only prevent async replication
to fully work on juju 3.5.{0,1} but not on ^3.4.3
Adjust assumes on metadata to ensure we only deploy on supported versions
> Fix assumes (k8s only)

- actions.yaml
- lib/charms/mysql/v0/async_replication.py
- tests/integration/high_availability/test_async_replication.py
`cluster-set-name` as parameter to `promote-to-primary` action is not in accordance with the spec.                  
Remove the action parameter
> DPE-4677 Remove parameter not in spec

- src/charm.py
A `config-change` triggered before pebble-ready will error out due container being unavailable.
Skip if no container is available. It's safe to do it, since workload configuration will take place on `pebble-ready` also.
> DPE-4768 Skip config change when no pebble connection

- lib/charms/mysql/v0/async_replication.py
Forgot to sync a minor, but important, state calculation step from async lib from VM
Fixes the async test failures on k8s
> Sync lib from vm

- lib/charms/mysql/v0/mysql.py
- src/relations/mysql_provider.py
- tests/integration/high_availability/test_async_replication.py
- tests/unit/test_database.py
Current username creation can lead to username collisions on cmr, due to it relying on relation id, that's only unique within a model.
Assemble the username with the model uuid and relation id, trimming to mysql's 32 char limit.
> DPE-4643 ensure username uniqueness

- tests/integration/helpers.py
- tests/integration/high_availability/high_availability_helpers.py
- tests/integration/high_availability/test_async_replication.py
- tests/integration/high_availability/test_upgrade.py
- tests/integration/high_availability/test_upgrade_from_stable.py
- tests/integration/high_availability/test_upgrade_rollback_incompat.py
- tests/integration/relations/test_database.py
- tests/integration/test_charm.py
- tests/integration/test_tls.py
Integration tests often fails on a [PVC failing to be created](https://github.com/canonical/mysql-k8s-operator/actions/runs/9983902668/job/27592545064#step:22:149)
Workaround it by not raise error on wait_for_idle when run after mysql-k8s deploy/scale commands (i.e. when PVC is created)
Credits to @lucasgameiroborges 
Fixes #378
> DPE-3557 Workaround pvc transient error

- poetry.lock
- pyproject.toml
- tests/integration/high_availability/test_node_drain.py
https://github.com/canonical/mysql-k8s-operator/issues/364
We traced log rotation hanging occasionally to a [pebble/ops issue](https://github.com/canonical/operator/issues/1246)) - there was a fix implemented in `ops 2.14.1`, but we have not yet updated our ops version to port in this fix
Update ops
> [DPE-3354] Update ops to ^2.15.0 to get pebble exec hanging fix

- src/prometheus_alert_rules/metrics_alert_rules.yaml
We would like to import a minimal set of alert rules from the [Awesome Prometheus Alert Rules blog](https://samber.github.io/awesome-prometheus-alerts/rules#mysql)
Import rules (noting slight modifications). Do not include any replication rules as they are not Group Replication related
> [DPE-2477] Add a minimal set of alert rules from the Awesome Prometheus Alert Rules blog

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/mysql/v0/async_replication.py
- lib/charms/mysql/v0/backups.py
- lib/charms/mysql/v0/mysql.py
- lib/charms/mysql/v0/s3_helpers.py
- lib/charms/mysql/v0/tls.py
- lib/charms/tempo_k8s/v1/charm_tracing.py
- lib/charms/tempo_k8s/v2/tracing.py
- src/mysql_k8s_helpers.py
We are leaking passwords when there's an issue creating a backup. For instance:
```
unit-mysql-k8s-0: 19:14:27 ERROR unit.mysql-k8s/0.juju-log Failed command: commands=['bash', '-c', 'set -o pipefail; xxtrabackup --defaults-file=/etc/mysql/my.cnf --defaults-group=mysqld --no-version-check --par
allel=12 --user=backups --password=vrEsWPEgo93NN8cv1a12nnZu --socket=/var/run/mysqld/mysqld.sock --lock-ddl --backup --stream=xbstream --xtrabackup-plugin-dir=/usr/lib64/xtrabackup/plugin --target-dir=/var/lib/m
ysql/xtra_backup_Eq2D --no-server-version-check | xbcloud put --curl-retriable-errors=7 --insecure --parallel=10 --md5 --storage=S3 --s3-region=us-east-1 --s3-bucket=mysql-backups-development --s3-endpoint=https
://s3.amazonaws.com --s3-api-version=auto --s3-bucket-lookup=auto …
```
> [DPE-4266] Strip passwords from command execute output and tracebacks

- src/charm.py
- src/log_rotate_manager.py
- src/relations/mysql.py
- src/relations/mysql_root.py
Recent changes from the way we check for `unit_initilized` is causing pebble errors when pebble is not yet ready on the workload container.
More clearly, `unit_initialized` was moved from a databag flag to a query to the mysqld itself, meaning if that unit was added to the current cluster.
1. Ensure calls to `unit_initialized` are only made if the workload container is ready (`can_connect() == True`).
2. During unrelated tests, It was noticed that default mysqld restart timeout value (30s) isn't enough for real world cases, so it's increased to 3600s.
> DPE-4933 Avoid early calls to unit_initialized

- src/charm.py
- tests/unit/test_charm.py
While testing, found a bug where scaling up after COS relationship is established.
The handler for `metrics-endpoint-relation-created` is running before the new unit is initialized (i.e. before pebble ready). Since the hook does `_reconcile_pebble` call, it try to start `mysqld_safe` before the data directory is initialized, causing the unit to fail to start.
Test for data_dir initialization on the handler for `metrics-endpoint-relation-created` and only call `_reconcile_pebble` if the data_dir is initialized.
> Fix metrics-endpoint created on scale up

- src/upgrade.py
`upgrade-relation-changed` can be triggered before workload container is ready on slow environments (looking at you GH).
Case it does, test for `unit_initialized` will fail, which can fail CI (on normal env, hook is retried until it passes).
Test for container availability
> DPE-5209 Fix unit-initialized test may break when run too early

- lib/charms/mysql/v0/mysql.py
- src/mysql_k8s_helpers.py
- tests/integration/conftest.py
- tests/integration/helpers.py
- tests/integration/high_availability/conftest.py
- tests/integration/high_availability/high_availability_helpers.py
- tests/integration/high_availability/test_async_replication.py
- tests/integration/high_availability/test_node_drain.py
- tests/integration/high_availability/test_replication.py
- tests/integration/high_availability/test_self_healing.py
- tests/integration/high_availability/test_upgrade.py
- tests/integration/high_availability/test_upgrade_from_stable.py
- tests/integration/relations/test_mysql_root.py
- tests/integration/test_backup_aws.py
- tests/integration/test_backup_ceph.py
- tests/integration/test_backup_gcp.py
- tests/integration/test_charm.py
- tests/unit/test_mysql_k8s_helpers.py
* Freeze DB test fails when waiting for credentials.
* multiple calls for same credentials during testing
* ops's `container.exec` timeout is not consistently working
* Fixture for credentials retrieval
* workaround for `container.exec` timeout
~~Propagate lib change back to VM~~
> DPE-5210 Common credentials fixture and `exec` timeout workaround

- tests/integration/helpers.py
- tests/integration/high_availability/conftest.py
- tests/integration/high_availability/test_log_rotation.py
- tests/integration/juju_.py
- tests/integration/test_charm.py
1. Even though the logrotation test kills the `log_rotate_dispatcher`, handling any event will restart the dispatcher process, leading the [following test failure](https://canonical.github.io/mysql-k8s-operator/2228/#categories/c7332569806a6cf9c4385feb46c38947/da8b6a29aef05e1f/)
2. Clear continuous writes may fail for various reasons during the self healing tests if the cluster is not healthy. For instance [this test run](https://github.com/canonical/mysql-k8s-operator/actions/runs/10625153069/job/29454851141#step:37:1037) or [this test run](https://github.com/canonical/mysql-k8s-operator/actions/runs/10633935256/job/29480518847#step:37:1077)
1. Check that the files that need to be rotated get rotated, with room for the lack of `audit.log` file (which may be rotated but not exist yet as …
> Attempt to stabilize failing integration tests

- src/relations/mysql_provider.py
- tests/unit/test_charm.py
- tests/unit/test_config.py
- tests/unit/test_database.py
Database request while container is not ready is causing uncaught exception.
Test for container connectivity and defer
> DPE-5385 fix/database requested wait container

- lib/charms/mysql/v0/mysql.py
- src/config.py
- tests/integration/connector.py
- tests/integration/test_saturate_max_connections.py
Port of admin_address on k8s.
VM PRs [PR#516](https://github.com/canonical/mysql-operator/pull/516) and [PR#520](https://github.com/canonical/mysql-operator/pull/520)
> DPE-5178 Admin address

- lib/charms/tempo_k8s/v2/tracing.py
- src/charm.py
In a debug statement, we are possibly referencing the `member_state` variable which may not be initialized if a `MySQLNoMemberStateError` exception is raised
Ensure that the `member_state` and `member_state_exists` variables (both logged) are always initialized if the code execution gets to the logger statement
> [DPE-5481] Ensure that uninitialized variable not referenced in _is_cluster_blocked helper

- tests/integration/test_multi_relations.py
The test test_multi_relations.py is randomly failing on libjuju 3.5.2.0 with Juju 3.6-beta2:
> juju.errors.JujuError: base "ubuntu@20.04/stable" is not supported, supported bases are: ubuntu@22.04
it is a known issue reported as https://github.com/juju/python-libjuju/issues/1090
As a (temporary?) workaround lets add a base here.
> [DPE-5480] Add base in test_multi_relations to workaround libjuju bug

- tests/integration/helpers.py
- tests/integration/high_availability/high_availability_helpers.py
- tests/integration/high_availability/test_k8s_endpoints.py
We are missing an integration test for https://github.com/canonical/mysql-k8s-operator/pull/501
Add integration test
> [DPE-4861] Add test to ensure correct k8s endpoints created for clusters with the same name

- src/charm.py
- src/upgrade.py
Some external hard to replicate bugs (e.g. #466 ) are even hard to debug to lack of useful logs.
(e.g. SQA tests are run with default info log level)
Decreased log level to some key initialization and upgrade steps
> DPE-4910 Change key logs from debug->info

- lib/charms/mysql/v0/mysql.py
- src/mysql_k8s_helpers.py
- tests/integration/high_availability/high_availability_helpers.py
- tests/integration/high_availability/test_node_drain.py
- tests/integration/high_availability/test_self_healing.py
- tests/integration/high_availability/test_upgrade_rollback_incompat.py
Recent PR #499 introduced new method on update status for the k8s charm.
The method calls node_count method that fails on all units if there's one unresponsive unit, causing regression in
freeze db tests, due responsive units not being able to relabel pods.  
Add timeout on node_count method to avoid hanging due unresponsive unit(s).
> DPE-5582 Timeout node count query

- src/prometheus_alert_rules/metrics_alert_rules.yaml
- tox.ini
Alert rule descriptions do not provide much guidance about what actions the user can take.
Improve the descriptions of the COS alert rule expressions.
The format should be:
1. What happened, or what is the problem
2. What can the user do to recover, or investigate further _(this is the part that's usually missing)_
Here is a good example:
```yaml
summary: PostgresSQL SSL compression active (instance {{ $labels.instance }})
description: |
Database connections have SSL compression enabled. This may add significant jitter in replication delay.
Replicas can turn off SSL compression via `sslcompression=0` in `recovery.conf`.
```
> [DPE-5659] Update COS alert rules

- lib/charms/mysql/v0/architecture.py
- src/charm.py
- tests/integration/helpers.py
- tests/integration/test_architecture.py
This PR introduces the usage of the newly created architecture lib (see [#560](https://github.com/canonical/mysql-operator/pull/560)) into the charm itself.
The shape of the integration tests, as well as the helper used to get the built charm in the architecture that mismatches the one of the host itself, have been adapted from the one Lucas created for PostgreSQL-k8s (see [code](https://github.com/canonical/postgresql-k8s-operator/blob/70a96ce33eb0de054b9297e3bd558f6ece54c0b0/tests/integration/test_wrong_arch.py)).
> [DPE-5588] Check against invalid arch

- tests/integration/high_availability/test_async_replication.py
- tests/integration/high_availability/test_crash_during_setup.py
test async and crash during setup consistently failing.
- **model calls for consume/offer breaking in tests**
- **use scaling strategy to reproduce crash of primary previous to secondaries join**
> fix: tests fixes #74

- config.yaml
- lib/charms/mysql/v0/mysql.py
- templates/logrotate.j2
- tests/integration/high_availability/test_log_rotation.py
- tests/unit/test_mysql_k8s_helpers.py
This PR bumps the `mysql` charm lib to its latest version. It does so by cherry picking changes from the following PRs:
- [Remove leftover MySQLBase methods](https://github.com/canonical/mysql-operator/pull/553).
- [\[DPE-5355\] Ensure logs flush](https://github.com/canonical/mysql-operator/pull/543).
- [\[DPE-6235\] Disable general_log and plugin audit_log_filter](https://github.com/canonical/mysql-operator/pull/574).
The cherry picked changes from the referenced PRs are those that affect the `mysql` charm lib itself, and all the necessary test changes to make integration tests pass. Additional improvements set on those PRs have been ignored.
[DPE-5355]: https://warthogs.atlassian.net/browse/DPE-5355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
> [MISC] Bump mysql charm lib version

- lib/charms/mysql/v0/mysql.py
- src/charm.py
- tests/integration/high_availability/test_self_healing.py
This PR adds logic to manually re-join a MySQL replica that has gone `OFFLINE`, to the cluster, whenever MySQL 8.0.21+ [auto re-join](https://dev.mysql.com/doc/refman/8.0/en/group-replication-responses-failure-rejoin.html) attempts have been exhausted.
There are edge cases where a MySQL instance that has lost connection to the cluster it originally belong to (i.e. `OFFLINE`), exhaust its automatic retries (by default 3 retries, with 5 mins between each, starting with MySQL 8.0.21). For those cases, a manual re-join should be performed.
---
Depends on https://github.com/canonical/mysql-k8s-operator/pull/563.
> [DPE-4375] Add cluster manual re-join handler

- metadata.yaml
- src/dependency.json
There is a new ROCK with an update of MySQL to v8.0.40
Update the ROCK tag and also update MySQL to v8.0.40
> [DPE-5063] Update MySQL to v8.0.40

- tests/integration/helpers.py
- tests/integration/high_availability/test_async_replication.py
- tests/integration/high_availability/test_upgrade_from_stable.py
- tests/integration/high_availability/test_upgrade_rollback_incompat.py
This PR cleans up multiple `@amd64_only` markers from the integration tests. There is an ARM64 stable release already.
- Not all `@amd64_only` markers could be removed, as there is no ARM64 MySQL snap breaking compatibility.
- Tests related to _rolling back when incompatibility_ have been improved to actually fail when they do not rollback.
> [DPE-6523] Remove AMD64-only test markers

- .gitignore
- src/charm.py
- src/mysql_k8s_helpers.py
1. Call to pebble fails due to missing readiness check
2. Call to pebble exec without a `wait` for the process (call is not executed)
Add said calls.
> fix: DPE-6521 Add missing check and wait for pebble calls

- lib/charms/mysql/v0/mysql.py
- src/charm.py
- src/constants.py
- src/mysql_k8s_helpers.py
- src/upgrade.py
- tests/integration/helpers.py
- tests/integration/high_availability/high_availability_helpers.py
- tests/integration/high_availability/manifests/extend_pebble_restart_delay.yml
- tests/integration/high_availability/manifests/reduce_pebble_restart_delay.yml
- tests/integration/high_availability/test_upgrade_rollback_incompat.py
- tests/unit/test_charm.py
- tests/unit/test_mysql_k8s_helpers.py
- tests/unit/test_upgrade.py
Mysqld_safe managed mysqld fails to restart when managed by pebble, due to mysqld_safe trapping SIGTERM, sent by pebble.
- ditch mysqld_usage, manage mysqld directly
- override `configure_instance` method to control restart within charm code, as mysql does not recognize pebble as a valid service manager
- refactor restart method to ditch rolling ops event defer and reuse unit recovery method (from upgrade code)
Merge after [PR#607](https://github.com/canonical/mysql-operator/pull/607)
fix #569
> fix: DPE-6485 Manage mysqld directly

- src/charm.py
When pebble related errors happen during mysqld bootstrap, charm code skips cleanup process that ensure method is idempotent.
Catch said errors to trigger cleanup process.
fixes #482 #535
> fix: dpe-5164 ensure failed bootstrap cleanup

- tests/integration/helpers.py
```
$ juju debug-log --model=test-upgrade-rollback-incompat-pz5a --level=WARNING --lines=100 --no-tail
ERROR setting --no-tail and --lines not valid
```
Avoid using `juju debug-log --lines --no-tail`. Replace `--lines` with `--limit`
> Avoid using incompatible juju debug-log options in test helper

- src/charm.py
- tests/unit/test_charm.py
- tests/unit/test_database.py
- tests/unit/test_upgrade.py
If charm pebble ready hooks run before k8s DNS is ready, the charm will configure mysql's `report_host` to `pod-name.<app-name>-endpoints`.
When the unit tries the recovery through mysqlsh api's `reboot_from_complete_outage`, shell will check the report_host against instances in the cluster metadata, which where previously
configured to the fully qualified domain name of the pod, failing the check and causing the recovery to fail.
Solution is fail whatever hook call the method for retrieving unit address, if address is not a valid fqdn.
By erroring out, juju should retry the hook, until k8s DNS is ready.
Fixes #597 #436
> fix: [DPE-6733] test for DNS availability

- src/charm.py
- src/relations/mysql_provider.py
- src/utils.py
- tests/unit/test_database.py
Related to router issue [#444](https://github.com/canonical/mysql-router-k8s-operator/issues/444)
Use absolute fqdn so DNS name search is skip, saving time and resources.
> feature: DPE-7534 use absolute fqdn for replication and consumers

- .github/workflows/approve_renovate_pr.yaml
- .github/workflows/check_pr.yaml
- .github/workflows/ci.yaml
- .github/workflows/promote.yaml
- .github/workflows/release.yaml
- .github/workflows/sync_docs.yaml
v32.x of data-platform-workflows [breaks compatibility](https://github.com/canonical/data-platform-workflows/pull/295#issue-3031537057) for promote action in charms not migrated to refresh-v3.
Stay with v31.x while charm is not migrated to refresh-v3
> misc: rollback data-workflows to v31.x

- lib/charms/mysql/v0/mysql.py
This PR is a port of [its counterpart](https://github.com/canonical/mysql-operator/pull/650) in MySQL VM operator.
The CI runs associated to this PR are expected to be flaky on every integration test depending on `8.0/edge` until this fix gets merged, and the published version in the `8.0/edge` channel gets updated. We must retry a few times after we get lucky, and merge as is, before defaulting to more extreme measures as commenting integration tests.
> [DPE-7648] Fix access to not populated instance label

- docs/reference/software-testing.md
- lib/charms/mysql/v0/mysql.py
- src/charm.py
- src/mysql_k8s_helpers.py
- src/relations/mysql.py
- src/relations/mysql_provider.py
- src/relations/mysql_root.py
- tests/integration/high_availability/high_availability_helpers.py
- tests/integration/relations/test_mysql_root.py
- tests/integration/roles/__init__.py
- tests/integration/roles/test_database_dba_role.py
- tests/integration/roles/test_instance_dba_role.py
- tests/integration/roles/test_instance_roles.py
- tests/spread/test_database_dba_role.py/task.yaml
- tests/spread/test_instance_dba_role.py/task.yaml
- tests/spread/test_instance_roles.py/task.yaml
- tests/unit/test_charm.py
- tests/unit/test_database.py
- tests/unit/test_mysql_k8s_helpers.py
This PR implements the set of predefined roles proposed in [this specification](https://docs.google.com/document/d/1U1tAWx9a7eb0HvdiS7lnSJS8oHqcl6F9PnAoRdcMjmc/edit?tab=t.0).
- Implemented MySQL lib [function](https://github.com/canonical/mysql-operator/blob/52b2c8fc3367e67fd0cdf750bda61e25b103d0a2/lib/charms/mysql/v0/mysql.py#L2693-L2709) to fully support the usage of `extra-user-roles` config argument.
- Harmonized MySQL config arguments to all user underscore (`_`) instead of mixing dashes and underscores.
> [DPE-7322] Support predefined roles

- tests/integration/test_osm_integration_bundle.py
- tests/spread/test_osm_integration_bundle.py/task.yaml
This PR fixes the OSM integration test, failing since September 13th (see [CI run](https://github.com/canonical/mysql-k8s-operator/actions/runs/17689695785)), by making the test juju-3 exclusive.
The mongo-k8s `5/...` set of channels have been closed, and there is no current version of the charm supporting both Juju 2 and Juju 3, according to Mehdi.
> [MISC] Fix OSM integration test

- docs/explanation/logs/audit-logs.md
- docs/explanation/security/index.md
- docs/how-to/monitoring-cos/enable-alert-rules.md
As part of SSDLC, we are missing specific advisory for event logging
Added text snippet to address event logging advisory.
Same as [PR#688](https://github.com/canonical/mysql-operator/pull/688)
> docs: DPE-8282 Security Event Logging advisory

- .github/workflows/ci.yaml
- .gitignore
- docs/how-to/deploy/terraform.md
- terraform/main.tf
- terraform/outputs.tf
- terraform/variables.tf
- terraform/versions.tf
- tox.ini
This PR tweaks the Terraform modules of the MySQL Server VM substrate, following the[ CC006 specification](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit?tab=t.0), which outlines how to organize Terrraform variables and outputs at the _charm_ level.
From the list of optional input variables:
> [DPE-7796] Tweak Terraform modules
